import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        Infinity: 'readonly',
        NaN: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        DOMPurify: 'readonly',
        module: 'readonly',
        require: 'readonly',
        SUPABASE_URL: 'readonly',
        SUPABASE_ANON_KEY: 'readonly',
        TABLES: 'readonly',
        DEFAULT_SHIFTS: 'readonly',
        DEFAULT_COMPETENCIES: 'readonly',
        DEFAULT_DISC_CONFIG: 'readonly',
        AVATAR_COLORS: 'readonly',
        AVATAR_ICONS: 'readonly',
        BOSS_BATTLES: 'readonly',
        DISC_MISSION_BOOSTS: 'readonly',
        ECONOMY_CURRENCY: 'readonly',
        ECONOMY_SHOP: 'readonly',
        LEGENDARY_RELICS: 'readonly',
        LIMITED_BADGES: 'readonly',
        MYSTERY_BOX_INTERVAL: 'readonly',
        MYSTERY_BOX_POOL: 'readonly',
        SHIFT_DATES: 'readonly',
        STREAK_BONUS: 'readonly',
        STREAK_MILESTONES: 'readonly',
        AUTH_EMAIL_DOMAIN: 'readonly',
        PROGRESS_TABLE: 'readonly',
        safeGet: 'writable',
        api: 'writable',
        STATE: 'writable',
        showView: 'readonly',
        showToast: 'readonly',
        esc: 'readonly',
        sanitizeText: 'readonly',
        displayName: 'readonly',
        displayNameEsc: 'readonly',
        initialsOf: 'readonly',
        getLevel: 'readonly',
        xpToNextLevel: 'readonly',
        rarityLabel: 'readonly',
        xpFromCompletion: 'readonly',
        xpFromBadge: 'readonly',
        calcXp: 'readonly',
        calcCurrency: 'readonly',
        calcStudentXP: 'readonly',
        authIsAdmin: 'readonly',
        authIsLoggedIn: 'readonly',
        authUsername: 'readonly',
        authSignUp: 'readonly',
        authSignIn: 'readonly',
        authSignOut: 'readonly',
        authGetSession: 'readonly',
        authGetProfile: 'readonly',
        authGetUser: 'readonly',
        LEVEL_NAMES: 'readonly',
        normalizeProgressRow: 'readonly',
        applyProgressToState: 'readonly',
        debouncedSaveProgress: 'readonly',
        snapshotStudentProgress: 'readonly',
        toProgressPayload: 'readonly',
        showAuthScreen: 'readonly',
        hideAuthScreen: 'readonly',
        applyRoleRestrictions: 'readonly',
        syncBottomBar: 'readonly',
        loadAllProgress: 'readonly',
        history: 'readonly',
        Event: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^(e|_|err)$' }],
      'no-undef': 'error',
      'no-redeclare': 'off',
      'no-constant-condition': 'warn',
      'no-empty': ['error', { allowEmptyCatch: true }],
      eqeqeq: 'warn',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'js/vendor/**',
      'dist/**',
      'backup/**',
      'gen-og.js',
      'deploy.sh',
      '*.config.js',
      'test/**',
    ],
  },
];
